/**
 * The boundary, as one testable rule.
 *
 * **Everything an LLM or a human AUTHORED is shared. Everything a machine derives
 * deterministically is not** — a clone regenerates it exactly from the code at a commit,
 * so shipping a copy buys nothing and costs one nobody can refresh or judge stale.
 *
 * The distinction is authorship, NOT who typed it. An agent's doc, an agent's flow and
 * an agent's triage proposal are authored work that cost real reading time and do not
 * come back if lost; analyzer output and the anchor/hash mapping are functions of the
 * code. Getting this backwards in either direction is expensive: drop authored content
 * and the team loses judgement nobody can reproduce; ship derived content and every
 * clone carries a stale copy of something it could have computed.
 *
 * Static, like `api-map.test.ts` and `review-via-render.test.ts`: what is being guarded
 * is a correspondence across files, and the drift is what needs catching.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

/**
 * The scope kinds that travel. Adding one is a decision this test makes you state.
 *
 * `standard/` is the one that needs a word, because it looks like it breaks the rule and
 * does not. Its EVENTS are all authored acts — drafting a spec, adding an operation,
 * ratifying, granting an acknowledgement, recording an audit, adjudicating a problem. The
 * requirements themselves are derived, but derived FROM THE LOG rather than from code:
 * every clone replays the same ratified operations and reaches the same rules, which is
 * why a requirement's id is a function of the operation that creates it. The rule this
 * file guards is that a function of the CODE must not travel, and no part of `standard/`
 * is one. See `docs/requirements-architecture.md`.
 */
const SHARED_KINDS = ["findings/", "bugs/", "docs/", "notes/", "walkthrough/", "triage/", "graph/"];

/**
 * `standard/` and `law/` travel and are deliberately NOT here.
 *
 * The sidecar is a git repo and sync moves the whole of it, so what travels is not decided
 * by `projectionFor` — that function decides what can be folded from ONE scope on its own.
 * The standard cannot: it folds from law (workspace) and evidence (universe) together,
 * because `spec.withdrawn` consults evidence to decide a law act. Registering it here would
 * let the generic loop fold either half alone and write a LAW-LESS standard under the real
 * key, which is a shipped bug this list would otherwise invite back.
 * `materializeUniverse` calls `cachedStandard` explicitly instead.
 */
const MERGED_KINDS = ["standard/", "law/"];

test("exactly the authored entity kinds travel", () => {
  const src = readFileSync("src/shared-projections.ts", "utf8");
  const registered = [...src.matchAll(/scope\.startsWith\("([a-z]+\/)"\)/g)].map((m) => m[1]!);
  assert.deepEqual(
    registered.sort(), [...SHARED_KINDS].sort(),
    "a scope kind was added or removed from `projectionFor`. Every kind here must be "
    + "AUTHORED — a person or an agent decided it. If the new one is derived from code, "
    + "it must not sync; if it is authored, add it to SHARED_KINDS and say so.",
  );
  // And the merged kinds must stay OUT of it, for the reason above.
  for (const k of MERGED_KINDS) {
    assert.ok(!registered.includes(k), `${k} is folded from two scopes and must not have a single-scope projection`);
  }
});

test("the standard is materialized explicitly, since nothing generic will do it", () => {
  // The other half of the rule above. Removing it from `projectionFor` without this is how
  // a ratification stops reaching the rows until somebody happens to read them.
  assert.match(
    readFileSync("src/ops-shared.ts", "utf8"), /await cachedStandard\(root, cfg\)/,
    "`materializeUniverse` no longer folds the standard, and `projectionFor` does not either",
  );
});

/**
 * Both ends, for every kind that can carry derived content.
 *
 * A publish check binds writers who ask. The FOLD is the only gate that binds a writer
 * this build did not write — an older client, a hand-written line, a future one that
 * forgets. This is not theory: removing only the publish half of the `process`/`step`
 * refusal left every flow event arriving and being silently dropped by the fold, and it
 * took a two-clone walk to find.
 */
const BOTH_ENDS: { what: string; fold: [string, RegExp]; publish: [string, RegExp] }[] = [
  {
    what: "analyzer-generated doc versions",
    fold: ["src/shared-docs.ts", /if \(v\.generatedBy\) continue;/],
    publish: ["src/ops-shared.ts", /regenerated by every machine from the code/],
  },
  {
    what: "graph-derived triage",
    fold: ["src/shared-triage.ts", /declared === "graph"/],
    publish: ["src/shared-triage.ts", /graph-derived triage does not travel/],
  },
  {
    what: "analyzer-generated edges",
    fold: ["src/shared-graph.ts", /if \(raw\.generatedBy\) continue;/],
    publish: ["src/shared-graph.ts", /filter\(\(e\) => !e\.generatedBy\)/],
  },
  // The three below shipped with the publish half only, which binds nobody but the
  // machine that ran it. Found by re-reading the fold against the tools it mirrors, not
  // by this test — which is why they are in it now.
  {
    // A provisional audit now TRAVELS — as a commit-discovered document, which nothing
    // folds (`provisional.ts`). What both ends still refuse is its entering the LOG, and
    // that is the half this registers: the document route is what makes the fold's guard
    // matter more, not less, because a client publishing one as an event is exactly the
    // mistake the new path invites.
    what: "provisional (branch-local) audits and problems in the event log",
    fold: ["src/shared-standard.ts", /if \(audit\.provisional\) break;/],
    publish: ["src/standard-publish.ts", /if \(!audit\.provisional\) return share\(root, \(l, s, a\) => publishAudit/],
  },
  {
    what: "an agent's debt acknowledgement",
    fold: ["src/shared-standard.ts", /ack\.basis === "debt" && e\.actor\.via/],
    publish: ["src/acknowledgements.ts", /principal\(root, input, "acknowledge debt"\)/],
  },
  {
    // Both ends must count a command the same way. They did NOT: `touchedCode` was tightened
    // to `some(passed)` because `{command: "false", passed: false}` had certified a rule, and
    // the fold was left on `ran.length` — so the identical audit the tool refused was accepted
    // by every clone. The earlier regexes here matched both ends while they meant different
    // things, which is why these pin the COUNTING RULE rather than the surrounding condition.
    //
    // The fold's copy now lives in `schema.ts`, inside `auditClaimStands` — which the fold
    // and the file reader share. The counting rule is still written TWICE, here and in
    // `audits.ts`'s `touchedCode`, and that is the pair this entry pins: it is the one
    // place the two ends historically disagreed, and the authoring surface keeps its own
    // copy so it can say which field is missing.
    what: "a conformant audit that touched no code",
    fold: ["src/schema.ts", /ev\.ran\?\.some\(\(r\) => r\.passed && !!r\.command\?\.trim\(\)\)/],
    publish: ["src/audits.ts", /e\.ran\?\.some\(\(r\) => r\.passed && !!r\.command\?\.trim\(\)\)/],
  },
  {
    // A scrub RESETS a rule's coverage clock, which is the quieting direction, so one that
    // skips an active pointer buys a fresh period without having looked at it. The fold
    // reads the pointer state from its own map — the team's view of what was active, not
    // the writer's account of it.
    what: "a covering audit that skipped one of the rule's active pointers",
    fold: ["src/shared-standard.ts", /if \(covering && watching\.some\(\(p\) => !seen\.has\(p\.id\)\)\) break;/],
    publish: ["src/audits.ts", /const missed = active\.filter\(\(p\) => !seen\.has\(p\.id\)\);/],
  },
  {
    // A falsifier that restates its criterion asserts nothing about what failure looks
    // like — it is the one vacuous form a machine can see, and it was refused only by the
    // authoring path. Same for an evidence kind outside the closed list: a vocabulary this
    // build cannot read is one no reader can either.
    what: "a criterion whose falsifier restates it",
    // `return false` rather than `return`: `applyOperation` reports whether it APPLIED, so
    // the caller can dry-run the whole ratification and refuse it as one. The guard is the
    // same; only what it hands back changed.
    fold: ["src/shared-standard.ts", /if \(flat\(op\.falsifier\) === flat\(op\.criterion\)\) return false;/],
    publish: ["src/requirements.ts", /the falsifier restates the criterion/],
  },
  {
    // A `demonstrated` check with no witnesses can NEVER be superseded, so it certifies a
    // check across every later rewrite of that check — the pathology the pin exists for,
    // reintroduced through the record meant to detect it.
    what: "a vacuity demonstration that can never be superseded",
    fold: ["src/shared-standard.ts", /check\.verdict === "demonstrated" && !check\.witnesses\?\.length/],
    publish: ["src/criteria.ts", /no \\`assertedBy\\` — there is no check to demonstrate/],
  },
  {
    // A PHANTOM observation names a pointer that is not on the rule, and fabricates history
    // for it: `pointerRates` tallies by pointer id and takes the requirement from the first
    // scrub that mentions it. Only the omission half of this gate was registered, which is
    // how the fold ended up with one of the two checks the tool has.
    what: "a covering audit observing a pointer that is not on the rule",
    fold: ["src/shared-standard.ts", /!watching\.some\(\(p\) => p\.id === o\.pointerId\)/],
    publish: ["src/audits.ts", /const phantom = observations\.filter/],
  },
  {
    // One look counted as several. Three copies of one observation reaches the default
    // `minObservations` from a single call and reports a pathology — the floor defeated
    // through the one door it does not watch.
    what: "the same pointer observed twice in one covering audit",
    fold: ["src/shared-standard.ts", /if \(seen\.size !== obs\.length\) break;/],
    publish: ["src/audits.ts", /if \(seen\.size !== observations\.length\)/],
  },
  {
    // A lint enumerates whatever is CHECKED OUT, so a pin from a feature branch is that
    // branch's population and not the team's — the same rule `shareAudit` follows.
    what: "a population pinned off the default branch",
    fold: ["src/shared-standard.ts", /if \(pin\.provisional\) break;/],
    publish: ["src/standard-publish.ts", /pin\.provisional\s*\n?\s*\? Promise\.resolve\(localOnly\)/],
  },
  {
    // A firing rate from a single look is not a rate. A policy admitting one would make the
    // scrub commit the exact error it exists to catch — a confident verdict from a check
    // that could not have produced one — for every clone that folded it.
    what: "a scrub policy whose observation floor cannot support a rate",
    fold: ["src/shared-standard.ts", /policy\.minObservations < 2\) break;/],
    publish: ["src/scrub.ts", /minObservations < 2\) \{/],
  },
  {
    // A pre-approved gap is part of an argument nobody has adopted yet, so it silences
    // nothing until ratification binds it — in the same act that creates the rule. Both
    // halves have to be at both ends: fold it `active` and a spec nobody ratifies leaves a
    // silencer nobody approved; bind without activating and the principal's approval never
    // takes effect on any clone but the ratifier's.
    what: "a gap that silences before its spec is adopted",
    fold: ["src/shared-standard.ts", /ack\.basis === "gap" \? "pending" : "active"/],
    publish: ["src/acknowledgements.ts", /state: "pending", grantedBy: actor/],
  },
  {
    what: "a ratification that binds a gap without activating it",
    fold: ["src/shared-standard.ts", /requirementId: rid, state: "active"/],
    publish: ["src/acknowledgements.ts", /requirementId: op\.requirementId, state: "active"/],
  },
  {
    // An audit that concluded nothing. The tool has always refused it; the fold never did,
    // which was found only when folding the scrub in brought a test that exercised it. Now
    // in `auditClaimStands`, which the fold and the file reader share.
    what: "an audit that records no finding",
    fold: ["src/schema.ts", /if \(!a\.finding\?\.trim\(\)\) return false;/],
    publish: ["src/audits.ts", /an audit needs a finding/],
  },
  {
    // A lint over zero members is GREEN, and green reads as conformant. With a query
    // language that was an edge case; with a lint it is the DEFAULT failure mode, which is
    // why the cheap mechanical layer exists at all — and why it has to exist at both ends.
    what: "a population pinned from a lint that examined nothing",
    fold: ["src/shared-standard.ts", /if \(pin\.basis === "lint" && !pin\.members\.length\) break;/],
    publish: ["src/population.ts", /a lint reporting zero members cannot be pinned/],
  },
  {
    // NARROWING a population until the violators fall outside it is the third laundering
    // door, after "amend the rule to match the code" and "declare the rule not yet
    // applicable". It can flip debt into a gap, which is silencing, so it is a principal's
    // act — and the fold decides it from the two member lists rather than from the writer.
    what: "an agent narrowing a rule's population",
    fold: ["src/shared-standard.ts", /if \(prior\.members\.some\(\(m\) => !after\.has\(m\.id\)\)\) break;/],
    publish: ["src/population.ts", /if \(delta\.narrows && isAgentActor\(actor\)\)/],
  },
  {
    // A pointer nobody can evaluate. The rationale is the only thing a later reader has to
    // judge a pointer BY — codemap cannot tell a well-aimed address from a laundered one —
    // so an empty one is the vacuity problem arriving at the record whose whole job is to
    // make auditing cheaper.
    what: "a pointer with no rationale",
    fold: ["src/shared-standard.ts", /if \(!p\.rationale\?\.trim\(\)\) break;/],
    publish: ["src/pointers.ts", /const rationale = input\.rationale\?\.trim\(\);/],
  },
  {
    // Retiring a pointer is a rule losing what watches it. It cannot silence a conformance
    // state — which is why it is open to any actor — but an unexplained one leaves the rule
    // unwatched with nothing on the record saying why, and unwatched must not read as calm.
    what: "a pointer retired with no reason",
    fold: ["src/shared-standard.ts", /if \(!reason\?\.trim\(\)\) break;/],
    publish: ["src/pointers.ts", /retiring a pointer needs a reason/],
  },
  // Three more the FOLD was missing, all found by a second reviewer running the fold on
  // hand-built events rather than by reading it. Two were the same shape as the
  // `touchedCode` entry above — a rule tightened at the writer and left permissive here —
  // and the third had never been at this end at all.
  //
  // **The first two are now ONE PREDICATE**, `auditClaimStands`, shared by the fold and by
  // `readProvisionalAudits`. That is a deliberate exception to this file's usual argument.
  // Two independent implementations catch each other's mistakes, and here they did not:
  // there were FOUR partly-independent audit validators — the writer, the fold, the file
  // reader and promotion — and every one of the audit findings in the 2026-08-28 review was
  // a disagreement between two of them. The authoring surface keeps its own, because its
  // job is to say which field is missing and why; the two surfaces where an audit ARRIVES
  // share, because neither has anybody to explain anything to.
  {
    what: "an audit that does not stand up as a record — no finding, wrong evidence for its outcome, or witnesses that do not match it",
    fold: ["src/shared-standard.ts", /if \(!auditClaimStands\(audit\)\) break;/],
    publish: ["src/provisional.ts", /&& auditClaimStands\(x\)/],
  },
  {
    // Withdrawal removes rules from the standard. It stays on the record as the act it is,
    // which needs the reason to be there — on both ends, not only where somebody typed it.
    what: "a withdrawal with no reason on the record",
    fold: ["src/shared-standard.ts", /if \(!str\(e\.data, "reason"\)\?\.trim\(\)\) break;/],
    publish: ["src/requirements.ts", /a withdrawal needs a `reason`/],
  },
  {
    // The evidence gate on a vacuity demonstration. `demonstrated` is the SILENCING
    // direction — it is what lets an audit lean on a check — so a demonstration recording
    // no method is the vacuous claim wearing the shape of evidence. Registered here from
    // the start rather than after the fold was found permissive, which is what the four
    // entries above cost.
    what: "a `demonstrated` vacuity check that records no method",
    fold: ["src/shared-standard.ts", /check\.verdict === "demonstrated" && !check\.method\?\.trim\(\)/],
    publish: ["src/criteria.ts", /input\.verdict === "demonstrated" && !method/],
  },
  {
    // Found independently by two reviews. The local path calls this asymmetry "structural
    // rather than advisory" and it was advisory anywhere but here: the fold took the
    // record's word, so an appended row naming a ratified `requirementId` and no operation
    // was accepted by every clone and reported a binding rule as `gap`.
    what: "a gap minted after the spec that introduced the rule was ratified",
    fold: ["src/shared-standard.ts", /specs\.get\(op\.specId\)\?\.status === "ratified"\) break;/],
    publish: ["src/acknowledgements.ts", /a gap may only be raised while the spec is still a draft/],
  },
  // Two more that had both ends in the code and neither end registered here, so a future
  // one-end deletion would have been silent. Found by walking the fold against the four
  // principal-gated verbs when they were first exposed as tools.
  //
  // Both fold patterns anchor on the CODE of the surrounding case, not on its comment:
  // `if (e.actor.via) break;` appears in two cases, so a bare match would be satisfied by
  // whichever survived, and a comment match would be satisfied by a comment above a guard
  // somebody had deleted.
  {
    what: "an agent's ratification of a spec",
    fold: ["src/shared-standard.ts", /sp\.status === "ratified"\) break;[\s\S]{0,240}?if \(e\.actor\.via\) break;/],
    publish: ["src/requirements.ts", /principal\(root, input, "ratify"\)/],
  },
  {
    what: "an agent's adjudication of a problem",
    fold: ["src/shared-standard.ts", /!p \|\| p\.disposition\) break;[\s\S]{0,240}?if \(e\.actor\.via\) break;/],
    publish: ["src/problems.ts", /principal\(root, input, "adjudicate a problem"\)/],
  },
  {
    // A `move_section` carries no `context`, so it is the one operation kind the fold's
    // staleness sweep does not cover by default — and a move whose source has been emptied
    // applies cleanly and does nothing. Silent, and on every clone but the one that ran it.
    what: "a section move that no longer means what it said",
    fold: ["src/shared-standard.ts", /if \(op\.kind === "move_section"\) return !moveApplicable/],
    publish: ["src/requirements.ts", /const bad = await checkMove\(root, op\.fromSection!/],
  },
  {
    // Reliance is a reference count, and the count is TOCTOU across clones: an audit or a
    // pointer appended elsewhere is invisible to the machine asking to withdraw. One end
    // alone lets a withdrawal race a citation and orphan it everywhere but there.
    what: "a withdrawal that would orphan something already citing the rule",
    fold: ["src/shared-standard.ts", /if \(foldReliance\(sp, mine, \{/],
    publish: ["src/requirements.ts", /const reliance = await relianceOn\(root, ops\);/],
  },
  {
    // Withdrawal is not a revert. A spec that changed something that already existed can
    // only be REPEALED, because putting the old statement back would witness it against
    // today's code as though the amendment had never happened.
    what: "withdrawing a spec that amended, retired or re-filed pre-existing state",
    fold: ["src/shared-standard.ts", /if \(mine\.some\(\(o\) => o\.kind !== "add_requirement" && o\.kind !== "add_criterion"\)\) break;/],
    publish: ["src/requirements.ts", /const changed = ops\.find\(\(o\) => o\.kind !== "add_requirement"/],
  },
];

test("derived content is refused at BOTH the publish surface and the fold", () => {
  for (const k of BOTH_ENDS) {
    for (const [end, [file, rx]] of [["fold", k.fold], ["publish", k.publish]] as const) {
      assert.match(
        readFileSync(file, "utf8"), rx,
        `${k.what} is no longer refused at the ${end} (${file}). The publish surface binds `
        + `writers who ask; the fold binds every writer. One end alone is not the rule.`,
      );
    }
  }
});

test("the anchor and hash mapping is not a shared entity kind", () => {
  // It is the most deterministic thing in the system — the same code at the same commit
  // under the same scheme mints the same ids and the same body hashes on every machine,
  // which is why a WITNESS travels as a receipt and the verdict about it never does.
  // Measured on the primary target: 5103 anchors, identical id+hash set across two
  // independent stores.
  for (const kind of ["anchors/", "snapshots/", "hashes/"]) {
    assert.ok(
      !SHARED_KINDS.includes(kind),
      `${kind} must not sync — it is a function of the code, and a clone that cannot `
      + `regenerate it has a build problem that copying somebody else's answer hides.`,
    );
  }
});
