/**
 * The boundary, as one testable rule.
 *
 * **Everything an LLM or a human AUTHORED is shared. Everything a machine derives
 * deterministically is not** — a clone regenerates it exactly from the code at a commit,
 * so shipping a copy buys nothing and costs one nobody can refresh or judge stale.
 *
 * The distinction is authorship, NOT who typed it. An agent's doc, an agent's flow and
 * an agent's triage proposal are authored work that cost real reading time and do not
 * come back if lost; analyzer output and the anchor/hash mapping are functions of the
 * code. Getting this backwards in either direction is expensive: drop authored content
 * and the team loses judgement nobody can reproduce; ship derived content and every
 * clone carries a stale copy of something it could have computed.
 *
 * Static, like `api-map.test.ts` and `review-via-render.test.ts`: what is being guarded
 * is a correspondence across files, and the drift is what needs catching.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

/**
 * The scope kinds that travel. Adding one is a decision this test makes you state.
 *
 * `standard/` is the one that needs a word, because it looks like it breaks the rule and
 * does not. Its EVENTS are all authored acts — drafting a spec, adding an operation,
 * ratifying, granting an acknowledgement, recording an audit, adjudicating a problem. The
 * requirements themselves are derived, but derived FROM THE LOG rather than from code:
 * every clone replays the same ratified operations and reaches the same rules, which is
 * why a requirement's id is a function of the operation that creates it. The rule this
 * file guards is that a function of the CODE must not travel, and no part of `standard/`
 * is one. See `docs/requirements-architecture.md`.
 */
const SHARED_KINDS = ["findings/", "bugs/", "docs/", "notes/", "walkthrough/", "triage/", "graph/", "standard/"];

test("exactly the authored entity kinds travel", () => {
  const src = readFileSync("src/shared-projections.ts", "utf8");
  const registered = [...src.matchAll(/scope\.startsWith\("([a-z]+\/)"\)/g)].map((m) => m[1]!);
  assert.deepEqual(
    registered.sort(), [...SHARED_KINDS].sort(),
    "a scope kind was added or removed from `projectionFor`. Every kind here must be "
    + "AUTHORED — a person or an agent decided it. If the new one is derived from code, "
    + "it must not sync; if it is authored, add it to SHARED_KINDS and say so.",
  );
});

/**
 * Both ends, for every kind that can carry derived content.
 *
 * A publish check binds writers who ask. The FOLD is the only gate that binds a writer
 * this build did not write — an older client, a hand-written line, a future one that
 * forgets. This is not theory: removing only the publish half of the `process`/`step`
 * refusal left every flow event arriving and being silently dropped by the fold, and it
 * took a two-clone walk to find.
 */
const BOTH_ENDS: { what: string; fold: [string, RegExp]; publish: [string, RegExp] }[] = [
  {
    what: "analyzer-generated doc versions",
    fold: ["src/shared-docs.ts", /if \(v\.generatedBy\) continue;/],
    publish: ["src/ops-shared.ts", /regenerated by every machine from the code/],
  },
  {
    what: "graph-derived triage",
    fold: ["src/shared-triage.ts", /declared === "graph"/],
    publish: ["src/shared-triage.ts", /graph-derived triage does not travel/],
  },
  {
    what: "analyzer-generated edges",
    fold: ["src/shared-graph.ts", /if \(raw\.generatedBy\) continue;/],
    publish: ["src/shared-graph.ts", /filter\(\(e\) => !e\.generatedBy\)/],
  },
  // The three below shipped with the publish half only, which binds nobody but the
  // machine that ran it. Found by re-reading the fold against the tools it mirrors, not
  // by this test — which is why they are in it now.
  {
    what: "provisional (branch-local) audits and problems",
    fold: ["src/shared-standard.ts", /if \(audit\.provisional\) break;/],
    publish: ["src/standard-publish.ts", /audit\.provisional \? Promise\.resolve\(localOnly\)/],
  },
  {
    what: "an agent's debt acknowledgement",
    fold: ["src/shared-standard.ts", /ack\.basis === "debt" && e\.actor\.via/],
    publish: ["src/acknowledgements.ts", /principal\(root, input, "acknowledge debt"\)/],
  },
  {
    // Both ends must count a command the same way. They did NOT: `touchedCode` was tightened
    // to `some(passed)` because `{command: "false", passed: false}` had certified a rule, and
    // the fold was left on `ran.length` — so the identical audit the tool refused was accepted
    // by every clone. The earlier regexes here matched both ends while they meant different
    // things, which is why these pin the COUNTING RULE rather than the surrounding condition.
    what: "a conformant audit that touched no code",
    fold: ["src/shared-standard.ts", /ev\.ran\?\.some\(\(r\) => r\.passed\)/],
    publish: ["src/audits.ts", /e\.ran\?\.some\(\(r\) => r\.passed\)/],
  },
  // Two more that had both ends in the code and neither end registered here, so a future
  // one-end deletion would have been silent. Found by walking the fold against the four
  // principal-gated verbs when they were first exposed as tools.
  //
  // Both fold patterns anchor on the CODE of the surrounding case, not on its comment:
  // `if (e.actor.via) break;` appears in two cases, so a bare match would be satisfied by
  // whichever survived, and a comment match would be satisfied by a comment above a guard
  // somebody had deleted.
  {
    what: "an agent's ratification of a spec",
    fold: ["src/shared-standard.ts", /sp\.status === "ratified"\) break;[\s\S]{0,240}?if \(e\.actor\.via\) break;/],
    publish: ["src/requirements.ts", /principal\(root, input, "ratify"\)/],
  },
  {
    what: "an agent's adjudication of a problem",
    fold: ["src/shared-standard.ts", /!p \|\| p\.disposition\) break;[\s\S]{0,240}?if \(e\.actor\.via\) break;/],
    publish: ["src/problems.ts", /principal\(root, input, "adjudicate a problem"\)/],
  },
];

test("derived content is refused at BOTH the publish surface and the fold", () => {
  for (const k of BOTH_ENDS) {
    for (const [end, [file, rx]] of [["fold", k.fold], ["publish", k.publish]] as const) {
      assert.match(
        readFileSync(file, "utf8"), rx,
        `${k.what} is no longer refused at the ${end} (${file}). The publish surface binds `
        + `writers who ask; the fold binds every writer. One end alone is not the rule.`,
      );
    }
  }
});

test("the anchor and hash mapping is not a shared entity kind", () => {
  // It is the most deterministic thing in the system — the same code at the same commit
  // under the same scheme mints the same ids and the same body hashes on every machine,
  // which is why a WITNESS travels as a receipt and the verdict about it never does.
  // Measured on the primary target: 5103 anchors, identical id+hash set across two
  // independent stores.
  for (const kind of ["anchors/", "snapshots/", "hashes/"]) {
    assert.ok(
      !SHARED_KINDS.includes(kind),
      `${kind} must not sync — it is a function of the code, and a clone that cannot `
      + `regenerate it has a build problem that copying somebody else's answer hides.`,
    );
  }
});
